FROM       centos
MAINTAINER cnit-jiangkaian <kajiang@chinacnit.com>
RUN yum install -y wget tar vim-enhanced passwd sudo yum-utils hostname net-tools man
RUN yum install -y gcc gcc-c++ git make automake cmake
RUN yum clean all

CMD /bin/bash
